[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "7oUZYs5kMhHAvtGSU2U5QpqMHpRcNJBSA1Deyswhr2j9"

[programs.localnet]
degenerator = "7oUZYs5kMhHAvtGSU2U5QpqMHpRcNJBSA1Deyswhr2j9"

[programs.mainnet]
degenerator = "7oUZYs5kMhHAvtGSU2U5QpqMHpRcNJBSA1Deyswhr2j9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://intensive-autumn-snowflake.solana-mainnet.quiknode.pro"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
