[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "EaMLjud2kCucAoFf2NGLtp3rVQeHaCR4N5XeL2bDZbRN"

[programs.localnet]
degenerator = "EaMLjud2kCucAoFf2NGLtp3rVQeHaCR4N5XeL2bDZbRN"

[programs.mainnet]
degenerator = "EaMLjud2kCucAoFf2NGLtp3rVQeHaCR4N5XeL2bDZbRN"

[registry]
url = "https://divine-ultra-diagram.solana-devnet.quiknode.pro"

[provider]
cluster = "https://divine-ultra-diagram.solana-devnet.quiknode.pro"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
