[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "BDz95W1MNQV5w1nNH8parxd5Q14oUgXFCRjXYns19Asw"

[programs.localnet]
degenerator = "BDz95W1MNQV5w1nNH8parxd5Q14oUgXFCRjXYns19Asw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
