[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "4dPcMAag9zD8Kj15FJiAUwRPCqrrBMk4wnyzbpKwT1wx"

[programs.localnet]
degenerator = "4dPcMAag9zD8Kj15FJiAUwRPCqrrBMk4wnyzbpKwT1wx"

[programs.mainnet]
degenerator = "4dPcMAag9zD8Kj15FJiAUwRPCqrrBMk4wnyzbpKwT1wx"

[registry]
url = "https://divine-ultra-diagram.solana-devnet.quiknode.pro"

[provider]
cluster = "https://divine-ultra-diagram.solana-devnet.quiknode.pro"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
