[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "BEnDHCog74Hico6frJS92yUNb55zGxRBh8LkxHZK5Mpe"

[programs.localnet]
degenerator = "BEnDHCog74Hico6frJS92yUNb55zGxRBh8LkxHZK5Mpe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
