[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "dLfUxieP6h4poxD4Lqm1YySK6AAUXY2cM98JyuQWmtk"

[programs.localnet]
degenerator = "dLfUxieP6h4poxD4Lqm1YySK6AAUXY2cM98JyuQWmtk"

[programs.mainnet]
degenerator = "dLfUxieP6h4poxD4Lqm1YySK6AAUXY2cM98JyuQWmtk"

[registry]
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
