[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "B3mDtybHy54Q1dYT36eb6fKcTK5QVFyTbyi76Te9vTEz"

[programs.localnet]
degenerator = "B3mDtybHy54Q1dYT36eb6fKcTK5QVFyTbyi76Te9vTEz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
