[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "2iB6387msY2gkiJJo4vw5GmhbxTtw1t5teg6a75v3Rgx"

[programs.localnet]
degenerator = "2iB6387msY2gkiJJo4vw5GmhbxTtw1t5teg6a75v3Rgx"

[programs.mainnet]
degenerator = "2iB6387msY2gkiJJo4vw5GmhbxTtw1t5teg6a75v3Rgx"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
