[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "6vSnb1s6HpMXdgjBP4M925iQ5YBj8FKTwPzqAJs8FQUc"

[programs.localnet]
degenerator = "9ToTPWXwvxdgQWofwWvviG2kTH8GkDKJoqJVoGNy8w8n"

[programs.mainnet]
degenerator = "EvyXTZ2uK2dAW4Vpqd2zWbPzyp9TYLZe4iuAwbTSM27f"

[registry]
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run jest"
