[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "9FgmwaUAKR5Vqqh4gPZoAGrPGUBtG4h5Mt8PdEZGTfy8"

[programs.localnet]
degenerator = "9FgmwaUAKR5Vqqh4gPZoAGrPGUBtG4h5Mt8PdEZGTfy8"

[programs.mainnet]
degenerator = "FofLf6BhJsj1HLvwLSXLMcsbxWHAZtEAFZ7EDcDGugNG"

[registry]
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run jest"
