[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "7yV76G3Wz1E2oUitNqSiFRKhaVs34LvPUTLZNS1ZbgGW"

[programs.localnet]
degenerator = "7yV76G3Wz1E2oUitNqSiFRKhaVs34LvPUTLZNS1ZbgGW"

[programs.mainnet]
degenerator = "7yV76G3Wz1E2oUitNqSiFRKhaVs34LvPUTLZNS1ZbgGW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://divine-ultra-diagram.solana-devnet.quiknode.pro"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run jest"
