[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "4DwsLqEToKjeZoEFgnGAiD48U7smxRmnKryhxQviYgfj"

[programs.localnet]
degenerator = "CNj8diaxBMDe3HQSTNzbruNfUCHeTvNrBtMUD6EgAx9V"

[programs.mainnet]
degenerator = "DFMxzshfQmXSY1QT3aQ2eWae738ZFYm6TVyZ4Uqdm5QM"

[registry]
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run jest"
