[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "HzxAfN9nRKNtRfbU3KNRpcKYBJUKoMpU733Vvsk3kTNh"

[programs.localnet]
degenerator = "HzxAfN9nRKNtRfbU3KNRpcKYBJUKoMpU733Vvsk3kTNh"

[programs.mainnet]
degenerator = "HzxAfN9nRKNtRfbU3KNRpcKYBJUKoMpU733Vvsk3kTNh"

[registry]
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run jest"
