[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "8441x9hay8ANHy5HE9iqK5DzyngeNy9ubdQz7XJW9naT"

[programs.localnet]
degenerator = "9FgmwaUAKR5Vqqh4gPZoAGrPGUBtG4h5Mt8PdEZGTfy8"

[programs.mainnet]
degenerator = "8vwVBn7gexccqn4mYpcxxquupzKuBhmTMVgoiCK3nzHV"

[registry]
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run jest"
