[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "CHoihhKjmqyrpjf5HcjdBwNmSqekGEX7jzzRCKFtRBah"

[programs.localnet]
degenerator = "9FgmwaUAKR5Vqqh4gPZoAGrPGUBtG4h5Mt8PdEZGTfy8"

[programs.mainnet]
degenerator = "C2npFofLubwGAwQ2UGH7yJ68y6Zj2hZUHnqqMpMM5x8e"

[registry]
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run jest"
