[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "8Ad2mhQUU1dQvwAbfksCjermBcZ15XjrGDGBQ6LWmrZB"

[programs.localnet]
degenerator = "8Ad2mhQUU1dQvwAbfksCjermBcZ15XjrGDGBQ6LWmrZB"

[programs.mainnet]
degenerator = "8Ad2mhQUU1dQvwAbfksCjermBcZ15XjrGDGBQ6LWmrZB"

[registry]
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run jest"
