[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "4PrrcfhkCqz8JF8wLHEzp5RcbNcYdAgode5hmhqfFf5y"

[programs.localnet]
degenerator = "4PrrcfhkCqz8JF8wLHEzp5RcbNcYdAgode5hmhqfFf5y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run jest"
