[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "4mjjK8dxPPEGUTxGFcvfyNY5rWntuaZJ9i6Diy6HwsZN"

[programs.localnet]
degenerator = "4mjjK8dxPPEGUTxGFcvfyNY5rWntuaZJ9i6Diy6HwsZN"

[programs.mainnet]
degenerator = "4mjjK8dxPPEGUTxGFcvfyNY5rWntuaZJ9i6Diy6HwsZN"

[registry]
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "https://divine-ultra-diagram.solana-devnet.quiknode.pro"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run jest"
