[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "4dPcMAag9zD8Kj15FJiAUwRPCqrrBMk4wnyzbpKwT1wx"

[programs.localnet]
degenerator = "4dPcMAag9zD8Kj15FJiAUwRPCqrrBMk4wnyzbpKwT1wx"

[programs.mainnet]
degenerator = "7d8qJx4mFJhxNHkGpgDcaK9DbokNJSVFKjtYq89ESFUa"

[registry]
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run jest"
