[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
degenerator = "4vQ5AyyGj42L2ttYcuRveu6NNFBUJ5apQiz2s4tJhLsp"

[programs.localnet]
degenerator = "9FgmwaUAKR5Vqqh4gPZoAGrPGUBtG4h5Mt8PdEZGTfy8"

[programs.mainnet]
degenerator = "6NXPzmaDdCTzPpwQ3sT2pXtQv5VKm2Xd3Rs6X95v6Afw"

[registry]
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run jest"
